### PR TITLE
mnap.py

### PR DESCRIPTION
**Pull request by DarpanMahato**
portscanner made in python with nmap

### CODE REVIEW

**Comment by ghost** [comment]
spelling mistake garnu vayexa😂😂

**Comment by ghost** [comment]
milaunu hunxa ki yettikai merge gardim?

**Comment by DarpanMahato** [comment]
mnap nai rakhya ho hehe

**Comment by ghost** [comment]
okay

**Comment by ghost** [comment]
folder milena😱😱

**Comment by ghost** [comment]
and maile merge handiye😱

**Comment by ghost** [comment]
ma yo file faldinxu feri hala hai

**Comment by ghost** [comment]
folder nai mistake vo maile folder milayo vane hacktoberfest ma error aaula so feri reupload in python folder

**Comment by DarpanMahato** [comment]
okay

**Pull request merged**
