### PR TITLE
 pangram_check.cpp

### PR DESCRIPTION
**Pull request by roymadhu123**
plz accept my pull request , it will be helpful for me to complete my hacktoberfest task .

### CODE REVIEW

**Comment by roymadhu123** [comment]
plz accept my pull request.

**Review by ghost — APPROVED** [review]
good

**Comment by roymadhu123** [comment]
its still showing as not accepted and neither in waiting state . can u plz
look over this once.

**Comment by ghost** [comment]
if you have already reloaded the hacktoberfest site once then you need to wait 15 mins for changes to be shown again in the site. Be patient and it will show after 15 mins till then keep reloading cause sometimes even after 15 mins if you reload only once changes will not be shown and when you do it twice then only changes will be shown

**Comment by ghost** [comment]
Next time please create a issue for this in issue section or comment in existing issue instead of PR comment section

**Comment by roymadhu123** [comment]
Ok, thanks.

**Pull request merged**
