### PR TITLE
Create right_view_of_a_binary tree.cpp

### PR DESCRIPTION
**Pull request by roymadhu123**
plz accept this pull request

### CODE REVIEW

**Comment by ghost** [comment]
Can you please send screenshot of output to this code and fix errors if any

**Comment by roymadhu123** [comment]
sure

**Comment by roymadhu123** [comment]
in my hacktoberfest profile , the code which i submitted under ur c++
folder showing as not accepted. what i should do now can u plz guide me?

**Comment by ghost** [comment]
If its this one then please send me screenshot for the output of this code and then I will guide through hacktoberfest

**Comment by roymadhu123** [comment]
Sure, here it is.

**Comment by ghost** [comment]
The image didn't come

**Comment by ghost** [comment]
Refresh your hacktoberfest profile page if no change occurs then refresh after 15 mins then boom your page will be refreshed again

**Comment by roymadhu123** [comment]
can i add more c++ &java code?

**Comment by roymadhu123** [comment]
Thanks a lot.
 Can u please accept my few more pull request , i have added in your c++
folder.
thanks .

**Pull request merged**
