### PR TITLE
Pyramidpattern.py

### PR DESCRIPTION
**Pull request by deepakstark01**
accept my merge request

### CODE REVIEW

**Comment by ghost** [comment]
Please don't make typo again and comment codes properly

**Comment by deepakstark01** [comment]
can you add hacktoberfest label

**Comment by deepakstark01** [comment]
it's showing these not accepted
image

**Comment by ghost** [comment]
It will take some time to refresh. Keep refreshing and it will put you in waiting time for 7 days and after that the count in 0/4 will increase. Till then it will show waiting. #Hacktoberfest #KeepContributing

**Comment by ghost** [comment]
@darakhshadeepak please add a new file in python folder and merge again. I changed the file folder to Python so there is possibility that although it puts you in waiting time after seven days it will be rejected by organizer. Add different file to avoid spamming.

**Comment by ghost** [comment]
Now add the file in Python folder and request to merge

**Pull request merged**
