### PR TITLE
 adding a c++ program for binary exponentiation

### PR DESCRIPTION
**Pull request by AshutoshJawanpuria**
This program is to return the power of a number by binary exponeentiations

### CODE REVIEW

**Comment by ghost** [comment]
Enjoy

**Comment by AshutoshJawanpuria** [comment]
Can I commit more codes??

**Comment by AshutoshJawanpuria** [comment]
Can I commit more codes @diwas777777 ... Will it be considered spammy??

**Comment by ghost** [comment]
You can add more codes as long as it does not contain any errors and are in right folders. Also do read README.md file for code of conducts

**Pull request merged**
