### PR TITLE
HelpdeskApplicationTest.java

### PR DESCRIPTION
**Pull request by Harsh-raj-x07**
Thanks

### CODE REVIEW

**Comment by Harsh-raj-x07** [comment]
Thanks for this 🙌🏼

**Comment by ghost** [comment]
may I know what this code does??

**Comment by Harsh-raj-x07** [comment]
> may I know what this code does??

HelpdeskappTest

**Comment by ghost** [comment]
can you elaborate

**Comment by Harsh-raj-x07** [comment]
> can you elaborate

Merged to kar do !
✌🏻

**Comment by ghost** [comment]
>>

**Pull request merged**
