### PR TITLE
Simple calculator using java

### PR DESCRIPTION
**Pull request by Dipesh0-0**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Sorry but your  program gives me error when I try to run it can you recheck your code and update with a screenshot of terminal successfully running your code please.

**Comment by Dipesh0-0** [comment]
image
fixed bug

**Comment by ghost** [comment]
Is my Project showing in hacktoberfest

I'm confused cause i can't see my own project

**Comment by Dipesh0-0** [comment]
Yes, bro, your project is showing on Hacktoberfest.
image

image

**Comment by ghost** [comment]
okay

**Comment by ghost** [comment]
thanks bro

**Pull request merged**
