### PR TITLE
added number guessing game made with python

### PR DESCRIPTION
**Pull request by vaibhavraj-exe**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Good game but the number range is too much can't guess any number

**Comment by vaibhavraj-exe** [comment]
> Good game but the number range is too much can't guess any number

Hey, I can fix that, in turn you can teach me how to do follow up PR  for fixing stuff (not doing this for hacktoberfest).
- Is it the same as before, I make changes, push it and then make a PR or is it something different ?
- And I hope my hacktoberfest tag wont be removed if I do a follow up PR.
- (Sorry for noob questions)

**Comment by ghost** [comment]
It doesn't need to be fixed now as the repo is for students let them learn something about variable and play the game

**Comment by ghost** [comment]
Making changes to a project is same as before you just need to open the project and edit the lines needed and then commit changes

**Comment by ghost** [comment]
and do a PR

**Comment by vaibhavraj-exe** [comment]
Thanks ! 👍

**Pull request merged**
